T6533: add reusable workflows
vyos/vyatta-cfg-system pull request #225
Opened 2024-06-29 18:50 UTC by kumvijaya

## Change Summary

T6533: add reusable workflows

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

https://vyos.dev/T6533

## Related PR(s)

## Component(s) name

## Proposed changes

## How to test

## Smoketest result

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

2024-06-30 06:48 UTC, c-po requested changes

2024-06-30 06:48 UTC, c-po commented on .github/workflows/add-pr-labels.yml
> +    uses: vyos/.github/.github/workflows/add-pr-labels.yml@current
Please use sagitta

2024-06-30 07:52 UTC, kumvijaya commented on .github/workflows/add-pr-labels.yml
> +    uses: vyos/.github/.github/workflows/add-pr-labels.yml@current
done

2024-06-30 08:31 UTC, c-po approved these changes

2024-07-02 14:05 UTC, dmbaturin approved these changes

2024-07-02 14:47 UTC, sever-sever approved these changes

2024-07-02 16:12 UTC, merged